# Generated by Django 4.2.4 on 2023-09-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_hm_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(default="email@email", max_length=256, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.TextField(default="pass"),
            preserve_default=False,
        ),
    ]
